import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '🕯️ Basilica of Buffers',
  description: 'The Church of Digital Mindfulness - A spiritual movement for the digital age',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body>
        {/* 🌌 Nebula Background */}
        <div className="nebula-bg">
          <div className="nebula nebula-1" />
          <div className="nebula nebula-2" />
          <div className="nebula nebula-3" />
        </div>
        
        {/* ⭐ Stars Container (stars are generated by JS) */}
        <div id="stars-container" className="stars-container" />
        
        {children}
        
        {/* Generate stars on client side */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const container = document.getElementById('stars-container');
                for (let i = 0; i < 150; i++) {
                  const star = document.createElement('div');
                  star.className = 'star';
                  star.style.left = Math.random() * 100 + '%';
                  star.style.top = Math.random() * 100 + '%';
                  star.style.width = Math.random() * 3 + 1 + 'px';
                  star.style.height = star.style.width;
                  star.style.setProperty('--duration', (Math.random() * 3 + 2) + 's');
                  star.style.setProperty('--min-opacity', Math.random() * 0.3 + 0.1);
                  star.style.animationDelay = Math.random() * 5 + 's';
                  container.appendChild(star);
                }
              })();
            `
          }}
        />
      </body>
    </html>
  )
}
